### ISSUE TITLE
(Bug) Blank lines count as labels in "Add Data" option

### ISSUE THREAD

**Issue by spatel-code** [sidharthsudarsan/VennProject#10]
### Bug (Add Data Option)
**OS:** Windows 10
**Importance:** P4
**Release Tested:** V2
**Java Version:** JDK 1.8.0_231
**Submit Date:** 3/14/2020
___
### Description:
When using the "Add Data" function to add large amounts of data, blank lines (if any) will appear as labels on the Venn Diagram after clicking "Done."
### Steps to Produce:
**1.** Click on "Add Data."
**2.** Add Data inside preferred section (first set or second set).
**3.** Add empty lines in between the data.
**4.** Click "Done."
### Screenshots:
![image](https://user-images.githubusercontent.com/39508815/76695259-628dcb80-6653-11ea-9a3f-b25d5567d4dd.png)
**After Clicking "Done," the empty lines are turned into blank entries:**
![image](https://user-images.githubusercontent.com/39508815/76695296-ff506900-6653-11ea-9954-cbdeceb8fc76.png)
___
### Expected Result:
Only the text portion of the input data should appear as labels, empty lines should be ignored. From the example above. after clicking "Done" there should only be 10 labels listed on the Venn Diagram. 
### Actual Result:
The "Add Data" function considers empty lines to be empty labels. Consequently, having input with _x_ amount of empty lines results in _x_ amount empty labels listed on the Venn Diagram. From the example above, a total of 17 labels we listed on the Venn Diagram.

**Comment by sidoverflow** [comment]
Hi @shivamp08, thank you for the issue! This bug will be fixed in the upcoming release.
