### ISSUE TITLE
(Enhancement) Improved Label Selection 

### ISSUE THREAD

**Issue by spatel-code** [sidharthsudarsan/VennProject#11]
### Enhancement (Label Selection)
**OS:** Windows 10
**Importance:** P4
**Release Tested:** V2
**Java Version:** JDK 1.8.0_231
**Submit Date:** 3/14/2020
___
### Description:
After the Venn Diagram gets crowded with multiple labels, it would be hard for the user to remember which label they clicked on when trying to change the text to Bold/Italics. It would help if there is an indicator on the label when it is selected.
### Steps to Produce:
1. Click on a label (Somehow indicate the selection by highlighting, changing border color, etc..)
2. Proceed to modify this label by using the Bold/Italics options.
### Screenshots:
![image](https://user-images.githubusercontent.com/39508815/76695829-13976480-665a-11ea-8068-62dec20df006.png)
![image](https://user-images.githubusercontent.com/39508815/76695834-1f832680-665a-11ea-8d8b-0a7bcc4d49af.png)
___
### Expected Result:
Clicking on a label should keep it highlighted, indicating to the user that any modifications done, will affect this label. 
### Actual Result:
Clicking on a label has no effect, the label is only highlighted orange if they cursor is hovering on top. Adding on, the label returns to normal, as soon as the cursor leaves. When the Venn Diagram is crowded, it makes it harder for the user to remember the label they selected.

**Comment by sidoverflow** [comment]
feature added
