### ISSUE TITLE
(Bug) Labels on a Venn Diagram are duplicated, when User updates their data.

### ISSUE THREAD

**Issue by spatel-code** [sidharthsudarsan/VennProject#12]
### Bug (Add Data Option)
**OS:** Windows 10
**Importance:** P2
**Release Tested:** V2
**Java Version:** JDK 1.8.0_231
**Submit Date:** 3/15/2020
___
### Description:
The "Add Data" option is used to fill the Venn Diagram with large amounts of data. However, if the User updates their data, only the changes should appear on the Venn Diagram, there should be no duplicates.
### Steps to Produce:
1. Click "Add Data." 
2. Input Data inside preferred sections (first set and or second set).
3. Click "Done."
4. Click "Add Data."
5. Change the previously entered data (add new entry, change a few lines, etc...)
6. Click "Done."
### Screenshots:
![image](https://user-images.githubusercontent.com/39508815/76706309-d7492000-66bc-11ea-95c2-29808668d7d5.png)
![image](https://user-images.githubusercontent.com/39508815/76706327-0069b080-66bd-11ea-8d68-0f40cfef003d.png)
![image](https://user-images.githubusercontent.com/39508815/76706367-4c1c5a00-66bd-11ea-964b-75c963345655.png)
![image](https://user-images.githubusercontent.com/39508815/76706396-8d146e80-66bd-11ea-9e6e-536141844bda.png)
___
### Expected Results:
When the User updates the previous data they entered, only the changes should appear on the Venn Diagram. From the example above, after updating the data, "New Entry" should be added to the diagram and "Second Set 3" should be removed, there should be no duplicates. 
### Actual Results:
After updating the data, original labels get duplicated along with the newly added changes. From the example above, there are five duplicates that appear after changing the data and clicking "Done."

**Comment by sidoverflow** [comment]
The *Add Data* feature is to ***add*** data to the diagram and not to *rewrite*. If you intend to *rewrite*, you can clear the existing data and *Add Data* again.
