### ISSUE TITLE
Not Able to Run The New Release Runnable Jar Bug.

### ISSUE THREAD

**Issue by Rushabh-Chauhan** [sidharthsudarsan/VennProject#14]
**Product:** venn.jar
**Version:** Release-2020-03-11-17-02-42
**Platform:** Dell Inspiron 5570
**OS:** Windows 10 Pro
**Java** **Version:** 1.8.0
**Priority:** P1

**Description:**

Not Able to run the new release runnable jar.

**Comment by sidoverflow** [comment]
I'm assuming you were able to run the *VennEver.jar* file since you posted two other issues.
