### ISSUE TITLE
Bold and Italic nonrevertible

### ISSUE THREAD

**Issue by Ahmed-Jawad-216340309** [sidharthsudarsan/VennProject#6]
OS: Windows10
Importance: P3
Release Tested: v2
Java Version: JDK 1.8.0_241
Description: Cannot unbold or unitalicize 
Steps to produce: Select text box, then click bold or italics, then undo
Expected Result: reverts text back to normal
Actual Result: the actions not involving bold or italics are undone

**Comment by sidoverflow** [comment]
fixed
