### ISSUE TITLE
(Enhancement) Circle Size

### ISSUE THREAD

**Issue by jdwalker17** [sidharthsudarsan/VennProject#8]
### Enhancement (resizing circle)

- OS: Windows10

- Importance: P5

- Release Tested: v2

- Java Version: JDK 13.0.2

- Submit Date: 3/14/2020

### Description: 
When Venn Diagram circle are resized, both circles are resized together. There is no way to have the user select a specific circle for resizing.
### Steps to produce: 

Press "Circle Size", once circle sized has been selected, drag slider to desired size.

### Screenshot:
![P3G1B2](https://user-images.githubusercontent.com/51487947/76689494-c17c2200-660c-11ea-9a30-d3797588262e.png)

### Current Result: 
Both circles are resized simultaneously as the slider is dragged up and down.  
### Enhanced Result: 
Being able to give the user the ability to select specific circles to resize. This enhancement could have 2 sliders, one for circle 1, and the other for circle 2. This would scale the intersection depending on how big or small the user specified each size to be.

**Comment by sidoverflow** [comment]
Venn Diagrams are usually made with equal circle sizes.
